/**
 * Seeds the 5 MVP recipes. Run with:
 *   NODE_ENV=development node src/db/seed/seedRecipes.js
 * Idempotent: upserts by slug.
 */
const { connectDB, disconnectDB } = require("../../config/db");
const Recipe = require("../../modules/recipes/recipe.model");

const recipes = [
  {
    title: "Rainbow Street Tacos",
    slug: "rainbow-street-tacos",
    description: "Build a taco with every color of the rainbow — a hands-on way to learn that eating colorfully means eating a variety of nutrients.",
    shortDescription: "Build a taco with every color of the rainbow.",
    coverImage: "recipe-tacos-cover.jpg",
    difficulty: "easy",
    ageGroups: ["7-9", "10-12"],
    preparationTimeMinutes: 15,
    cookingTimeMinutes: 10,
    totalTimeMinutes: 25,
    ingredients: [
      { name: "Soft corn tortillas", quantity: 8, unit: "count", category: "Bakery" },
      { name: "Bell peppers (mixed colors)", quantity: 3, unit: "count", category: "Produce" },
      { name: "Black beans", quantity: 1, unit: "cup", category: "Pantry" },
      { name: "Sweet corn", quantity: 1, unit: "cup", category: "Produce" },
      { name: "Cheddar cheese, shredded", quantity: 1, unit: "cup", category: "Dairy" },
      { name: "Lime", quantity: 1, unit: "count", category: "Produce", optional: true },
    ],
    steps: [
      {
        stepNumber: 1,
        title: "Wash your hands",
        instruction: "Wash your hands with soap and water for 20 seconds before you start cooking.",
        simpleInstruction: "Wash your hands really well!",
        safetyLevel: "none",
        parentAssistanceRequired: false,
      },
      {
        stepNumber: 2,
        title: "Wash the veggies",
        instruction: "Rinse the bell peppers and corn under cool running water.",
        simpleInstruction: "Give the peppers and corn a cool water bath.",
        safetyLevel: "none",
        parentAssistanceRequired: false,
      },
      {
        stepNumber: 3,
        title: "Chop the peppers",
        instruction: "Ask a grown-up to help chop the bell peppers into small pieces.",
        simpleInstruction: "A grown-up helps chop the peppers into tiny pieces.",
        safetyLevel: "sharpTool",
        parentAssistanceRequired: true,
      },
      {
        stepNumber: 4,
        title: "Warm the tortillas",
        instruction: "Ask a grown-up to warm the tortillas in a dry pan for about 30 seconds per side.",
        simpleInstruction: "A grown-up warms up the tortillas.",
        estimatedDurationSeconds: 60,
        safetyLevel: "lowHeat",
        parentAssistanceRequired: true,
      },
      {
        stepNumber: 5,
        title: "Layer the beans and corn",
        instruction: "Spoon black beans and sweet corn onto each tortilla.",
        simpleInstruction: "Add a scoop of beans and a scoop of corn.",
        safetyLevel: "none",
        parentAssistanceRequired: false,
      },
      {
        stepNumber: 6,
        title: "Add the rainbow peppers",
        instruction: "Sprinkle the chopped bell peppers over the top.",
        simpleInstruction: "Sprinkle on your colorful peppers.",
        safetyLevel: "none",
        parentAssistanceRequired: false,
      },
      {
        stepNumber: 7,
        title: "Top with cheese",
        instruction: "Add a sprinkle of shredded cheddar cheese.",
        simpleInstruction: "Add a little cheese on top.",
        safetyLevel: "none",
        parentAssistanceRequired: false,
      },
      {
        stepNumber: 8,
        title: "Squeeze and enjoy",
        instruction: "Squeeze a bit of lime over the top if you like, fold, and enjoy your rainbow taco!",
        simpleInstruction: "Squeeze some lime on top and dig in!",
        safetyLevel: "none",
        parentAssistanceRequired: false,
      },
    ],
    cookingSkills: ["measuring", "assembling", "safe knife awareness"],
    nutritionLearning: ["Eating a rainbow of colors means a variety of vitamins", "Beans are a great plant-based protein"],
    funFacts: ["Bell peppers actually have more vitamin C than an orange!"],
    learningObjectives: ["Recognize different vegetable colors and what they contribute nutritionally"],
    xpReward: 40,
    unlockRequirements: { type: "always" },
    supervisionRequired: true,
    knifeSafety: true,
    heatSafety: true,
    allergenInformation: ["dairy"],
    requiresParentVerification: true,
    status: "published",
  },
  {
    title: "Smiley Jack Pancakes",
    slug: "smiley-jack-pancakes",
    description: "Fluffy whole-wheat pancakes with a fruity smile on top — a fun way to talk about whole grains and portion-sized toppings.",
    shortDescription: "Fluffy pancakes with a fruity smile on top.",
    coverImage: "recipe-pancakes-cover.jpg",
    difficulty: "easy",
    ageGroups: ["4-6", "7-9"],
    preparationTimeMinutes: 10,
    cookingTimeMinutes: 5,
    totalTimeMinutes: 15,
    ingredients: [
      { name: "Whole wheat flour", quantity: 1, unit: "cup", category: "Baking" },
      { name: "Milk", quantity: 1, unit: "cup", category: "Dairy" },
      { name: "Egg", quantity: 1, unit: "count", category: "Dairy" },
      { name: "Blueberries", quantity: 0.5, unit: "cup", category: "Produce" },
      { name: "Banana", quantity: 1, unit: "count", category: "Produce" },
      { name: "Maple syrup", quantity: 2, unit: "tbsp", category: "Pantry", optional: true },
    ],
    steps: [
      {
        stepNumber: 1,
        title: "Wash your hands",
        instruction: "Wash your hands with soap and water before you start.",
        simpleInstruction: "Wash your hands!",
        safetyLevel: "none",
        parentAssistanceRequired: false,
      },
      {
        stepNumber: 2,
        title: "Mix the batter",
        instruction: "Whisk together the flour, milk, and egg in a big bowl until smooth.",
        simpleInstruction: "Stir the flour, milk, and egg together until smooth.",
        safetyLevel: "none",
        parentAssistanceRequired: false,
      },
      {
        stepNumber: 3,
        title: "Cook the pancakes",
        instruction: "Ask a grown-up to help pour small circles of batter onto a warm, lightly buttered pan and flip when bubbles form.",
        simpleInstruction: "A grown-up cooks your pancakes on the stove.",
        estimatedDurationSeconds: 180,
        safetyLevel: "highHeat",
        parentAssistanceRequired: true,
      },
      {
        stepNumber: 4,
        title: "Stack them up",
        instruction: "Stack 2-3 pancakes on a plate.",
        simpleInstruction: "Stack up your pancakes.",
        safetyLevel: "none",
        parentAssistanceRequired: false,
      },
      {
        stepNumber: 5,
        title: "Make the smiley face",
        instruction: "Slice the banana into coins for eyes and arrange blueberries for a smile. Drizzle a little maple syrup if you'd like.",
        simpleInstruction: "Use banana slices for eyes and blueberries for a smile!",
        safetyLevel: "none",
        parentAssistanceRequired: false,
      },
    ],
    cookingSkills: ["mixing", "flipping (with help)", "plating"],
    nutritionLearning: ["Whole wheat flour has more fiber than white flour", "Fruit toppings add vitamins without needing lots of added sugar"],
    funFacts: ["Bananas are technically berries, botanically speaking!"],
    learningObjectives: ["Understand whole grains vs. refined grains"],
    xpReward: 30,
    unlockRequirements: { type: "always" },
    supervisionRequired: true,
    knifeSafety: false,
    heatSafety: true,
    allergenInformation: ["dairy", "egg", "gluten"],
    requiresParentVerification: true,
    status: "published",
  },
  {
    title: "Mini Rainbow Sliders",
    slug: "mini-rainbow-sliders",
    description: "Bite-sized burgers loaded with colorful veggies — a hands-on lesson in building a balanced plate.",
    shortDescription: "Bite-sized burgers loaded with veggies.",
    coverImage: "recipe-burgers-cover.jpg",
    difficulty: "medium",
    ageGroups: ["7-9", "10-12"],
    preparationTimeMinutes: 15,
    cookingTimeMinutes: 15,
    totalTimeMinutes: 30,
    ingredients: [
      { name: "Whole wheat slider buns", quantity: 6, unit: "count", category: "Bakery" },
      { name: "Lean ground turkey", quantity: 1, unit: "lb", category: "Meat" },
      { name: "Tomato", quantity: 1, unit: "count", category: "Produce" },
      { name: "Avocado", quantity: 1, unit: "count", category: "Produce" },
      { name: "Lettuce", quantity: 4, unit: "count", category: "Produce" },
      { name: "Cheddar cheese slices", quantity: 6, unit: "count", category: "Dairy", optional: true },
    ],
    steps: [
      {
        stepNumber: 1,
        title: "Wash your hands",
        instruction: "Wash your hands thoroughly, especially before handling raw meat.",
        simpleInstruction: "Wash your hands really well!",
        safetyLevel: "none",
        parentAssistanceRequired: false,
      },
      {
        stepNumber: 2,
        title: "Form the patties",
        instruction: "With a grown-up, gently shape the ground turkey into 6 small slider-sized patties. Wash hands again after handling raw meat.",
        simpleInstruction: "Shape the meat into little burger patties with a grown-up.",
        safetyLevel: "none",
        parentAssistanceRequired: true,
      },
      {
        stepNumber: 3,
        title: "Cook the patties",
        instruction: "Ask a grown-up to cook the patties on a pan or grill until fully cooked through (internal temperature 165°F).",
        simpleInstruction: "A grown-up cooks your patties until they're done.",
        estimatedDurationSeconds: 480,
        safetyLevel: "highHeat",
        parentAssistanceRequired: true,
      },
      {
        stepNumber: 4,
        title: "Slice the veggies",
        instruction: "Ask a grown-up to help slice the tomato and avocado.",
        simpleInstruction: "A grown-up helps slice the tomato and avocado.",
        safetyLevel: "sharpTool",
        parentAssistanceRequired: true,
      },
      {
        stepNumber: 5,
        title: "Build your slider",
        instruction: "Layer lettuce, patty, tomato, avocado, and cheese between bun halves.",
        simpleInstruction: "Stack it all up between the buns!",
        safetyLevel: "none",
        parentAssistanceRequired: false,
      },
      {
        stepNumber: 6,
        title: "Add the top bun",
        instruction: "Place the top bun on and press down gently.",
        simpleInstruction: "Put the top bun on!",
        safetyLevel: "none",
        parentAssistanceRequired: false,
      },
      {
        stepNumber: 7,
        title: "Serve and enjoy",
        instruction: "Plate your sliders and enjoy your balanced, colorful meal!",
        simpleInstruction: "Time to eat your yummy creation!",
        safetyLevel: "none",
        parentAssistanceRequired: false,
      },
    ],
    cookingSkills: ["food safety with raw meat", "assembling", "portioning"],
    nutritionLearning: ["Lean protein plus vegetables makes a balanced plate", "Avocado provides healthy fats"],
    funFacts: ["The word 'slider' comes from how easily these small burgers slide down!"],
    learningObjectives: ["Build a balanced plate with protein, grains, and vegetables", "Understand basic raw-meat food safety"],
    xpReward: 45,
    unlockRequirements: { type: "levelAtLeast", value: 2 },
    supervisionRequired: true,
    knifeSafety: true,
    heatSafety: true,
    allergenInformation: ["dairy", "gluten"],
    requiresParentVerification: true,
    status: "published",
  },
  {
    title: "Golden Mac & Magic",
    slug: "golden-mac-and-magic",
    description: "Homemade mac and cheese — the science of stretchy, melty cheese, made a little more balanced with a whole-grain twist.",
    shortDescription: "The science of stretchy, melty cheese.",
    coverImage: "recipe-mac-cover.jpg",
    difficulty: "easy",
    ageGroups: ["4-6", "7-9"],
    preparationTimeMinutes: 10,
    cookingTimeMinutes: 10,
    totalTimeMinutes: 20,
    ingredients: [
      { name: "Whole wheat elbow pasta", quantity: 2, unit: "cup", category: "Pantry" },
      { name: "Cheddar cheese, shredded", quantity: 1.5, unit: "cup", category: "Dairy" },
      { name: "Butter", quantity: 2, unit: "tbsp", category: "Dairy" },
      { name: "Milk", quantity: 1, unit: "cup", category: "Dairy" },
      { name: "Breadcrumbs", quantity: 0.25, unit: "cup", category: "Pantry", optional: true },
      { name: "Paprika", quantity: 0.5, unit: "tsp", category: "Pantry", optional: true },
    ],
    steps: [
      {
        stepNumber: 1,
        title: "Wash your hands",
        instruction: "Wash your hands with soap and water.",
        simpleInstruction: "Wash your hands!",
        safetyLevel: "none",
        parentAssistanceRequired: false,
      },
      {
        stepNumber: 2,
        title: "Boil the pasta",
        instruction: "Ask a grown-up to boil the pasta in salted water according to package directions, then drain.",
        simpleInstruction: "A grown-up boils the pasta for you.",
        estimatedDurationSeconds: 600,
        safetyLevel: "highHeat",
        parentAssistanceRequired: true,
      },
      {
        stepNumber: 3,
        title: "Melt the butter",
        instruction: "With a grown-up, melt the butter in a pot over low heat.",
        simpleInstruction: "A grown-up melts the butter with you watching.",
        safetyLevel: "lowHeat",
        parentAssistanceRequired: true,
      },
      {
        stepNumber: 4,
        title: "Stir in milk and cheese",
        instruction: "Add the milk, then stir in the shredded cheese a little at a time until melted and smooth.",
        simpleInstruction: "Stir in the milk, then add cheese bit by bit until melty!",
        safetyLevel: "lowHeat",
        parentAssistanceRequired: true,
      },
      {
        stepNumber: 5,
        title: "Combine with pasta",
        instruction: "Pour the cheese sauce over the pasta and stir until every piece is coated.",
        simpleInstruction: "Mix the cheesy sauce into the pasta.",
        safetyLevel: "none",
        parentAssistanceRequired: false,
      },
      {
        stepNumber: 6,
        title: "Top and serve",
        instruction: "Sprinkle breadcrumbs and paprika on top if using, then serve warm.",
        simpleInstruction: "Add a sprinkle on top and it's ready!",
        safetyLevel: "none",
        parentAssistanceRequired: false,
      },
    ],
    cookingSkills: ["boiling (with help)", "stirring", "sauce-making basics"],
    nutritionLearning: ["Whole wheat pasta has more fiber than regular pasta", "Cheese and milk are good calcium sources"],
    funFacts: ["Cheese gets stretchy because of how its proteins react to heat!"],
    learningObjectives: ["Understand calcium-rich foods and whole grains"],
    xpReward: 30,
    unlockRequirements: { type: "always" },
    supervisionRequired: true,
    knifeSafety: false,
    heatSafety: true,
    allergenInformation: ["dairy", "gluten"],
    requiresParentVerification: true,
    status: "published",
  },
  {
    title: "Garden Rainbow Skewers",
    slug: "garden-rainbow-skewers",
    description: "No-cook rainbow snacks with fruit and veggies — the easiest recipe for building confidence with zero heat or knives needed for the child's part.",
    shortDescription: "No-cook rainbow snacks with fruit & veg.",
    coverImage: "recipe-skewers-cover.jpg",
    difficulty: "easy",
    ageGroups: ["4-6", "7-9"],
    preparationTimeMinutes: 10,
    cookingTimeMinutes: 0,
    totalTimeMinutes: 10,
    ingredients: [
      { name: "Strawberries", quantity: 6, unit: "count", category: "Produce" },
      { name: "Pineapple chunks", quantity: 1, unit: "cup", category: "Produce" },
      { name: "Kiwi", quantity: 2, unit: "count", category: "Produce" },
      { name: "Blueberries", quantity: 0.5, unit: "cup", category: "Produce" },
      { name: "Red bell pepper", quantity: 1, unit: "count", category: "Produce" },
      { name: "Honey", quantity: 1, unit: "tbsp", category: "Pantry", optional: true },
    ],
    steps: [
      {
        stepNumber: 1,
        title: "Wash your hands and produce",
        instruction: "Wash your hands, then rinse all the fruit and pepper under cool water.",
        simpleInstruction: "Wash your hands, then rinse all the fruit!",
        safetyLevel: "none",
        parentAssistanceRequired: false,
      },
      {
        stepNumber: 2,
        title: "Prep the pieces",
        instruction: "Ask a grown-up to help slice the kiwi and pepper into bite-sized pieces (strawberries, pineapple, and blueberries can stay whole or as-is).",
        simpleInstruction: "A grown-up helps cut the kiwi and pepper into little pieces.",
        safetyLevel: "sharpTool",
        parentAssistanceRequired: true,
      },
      {
        stepNumber: 3,
        title: "Thread the skewer",
        instruction: "Carefully thread the fruit and pepper pieces onto a skewer in rainbow order: red, orange, yellow, green, blue/purple.",
        simpleInstruction: "Put the pieces on your skewer in rainbow order!",
        safetyLevel: "none",
        parentAssistanceRequired: true,
      },
      {
        stepNumber: 4,
        title: "Drizzle and enjoy",
        instruction: "Add a light drizzle of honey if you'd like, then enjoy your rainbow snack!",
        simpleInstruction: "Add a little honey if you want, and enjoy!",
        safetyLevel: "none",
        parentAssistanceRequired: false,
      },
    ],
    cookingSkills: ["food prep without heat", "pattern-building", "fine motor skills"],
    nutritionLearning: ["Eating many colors of produce means many different vitamins", "Bell peppers are a fruit botanically but used as a vegetable in cooking"],
    funFacts: ["A red bell pepper has more vitamin C than an orange!"],
    learningObjectives: ["Recognize a wide variety of fruits and vegetables by color"],
    xpReward: 25,
    unlockRequirements: { type: "always" },
    supervisionRequired: false,
    knifeSafety: true,
    heatSafety: false,
    allergenInformation: [],
    requiresParentVerification: false,
    status: "published",
  },
];

async function seed() {
  await connectDB();
  for (const r of recipes) {
    // eslint-disable-next-line no-await-in-loop
    await Recipe.findOneAndUpdate({ slug: r.slug }, { $set: r }, { upsert: true, new: true, setDefaultsOnInsert: true });
    // eslint-disable-next-line no-console
    console.log(`✅ Seeded recipe: ${r.title} (${r.steps.length} steps)`);
  }
  await disconnectDB();
}

seed()
  .then(() => {
    // eslint-disable-next-line no-console
    console.log("🌱 Recipe seeding complete");
    process.exit(0);
  })
  .catch((err) => {
    // eslint-disable-next-line no-console
    console.error("Seed failed:", err);
    process.exit(1);
  });
