const ChildProfile = require("../children/childProfile.model");
const GameSession = require("../games/gameSession.model");
const Game = require("../games/game.model");
const RecipeProgress = require("../recipes/recipeProgress.model");
const Recipe = require("../recipes/recipe.model");
const XPTransaction = require("../xp/xpTransaction.model");
const groceryService = require("../grocery/grocery.service");
const ApiError = require("../../utils/ApiError");
const { parsePagination, buildPaginationMeta } = require("../../utils/pagination");
const { getOwnedChild } = require("../../utils/getOwnedChild");

const SEVEN_DAYS_MS = 7 * 24 * 60 * 60 * 1000;



/**
 * Date-range filtering is done in application code rather than a Mongo
 * `$gte` query. Two reasons: (1) it keeps this module portable across the
 * real Mongoose model and this codebase's in-memory test fakes, which
 * don't implement range operators; (2) at MVP scale (a handful of
 * sessions per child per week) this is negligible cost. The database
 * architecture doc already flags the production-scale answer: a
 * materialized `WeeklyProgressSummary` regenerated by a nightly job,
 * behind this exact same API contract, so switching later doesn't touch
 * any client code.
 */
function withinLastDays(date, days) {
  if (!date) return false;
  return Date.now() - new Date(date).getTime() <= days * 24 * 60 * 60 * 1000;
}

// ---------------------------------------------------------------------------
// OVERVIEW
// ---------------------------------------------------------------------------

async function getOverview(childId, familyId) {
  const child = await getOwnedChild(childId, familyId);

  const [gameSessions, recipeProgresses, xpTransactions] = await Promise.all([
    GameSession.find({ childProfile: child._id, status: "completed" }),
    RecipeProgress.find({ child: child._id, status: "completed" }),
    XPTransaction.find({ childProfile: child._id }),
  ]);

  const weeklyXpEarned = (Array.isArray(xpTransactions) ? xpTransactions : [])
    .filter((t) => withinLastDays(t.createdAt, 7))
    .reduce((sum, t) => sum + t.amount, 0);

  const totalActivityCount =
    (Array.isArray(gameSessions) ? gameSessions.length : 0) + (Array.isArray(recipeProgresses) ? recipeProgresses.length : 0);

  const recentActivity = await buildRecentActivity(child._id, 10);

  return {
    child: { _id: child._id, displayName: child.displayName, avatarColor: child.avatarColor, currentLevel: child.currentLevel },
    totalActivityCount,
    weeklyXpEarned,
    currentStreak: child.currentStreak,
    longestStreak: child.longestStreak,
    totalXP: child.totalXP,
    recentActivity,
  };
}

async function buildRecentActivity(childId, limit) {
  const [gameSessions, recipeProgresses] = await Promise.all([
    GameSession.find({ childProfile: childId, status: "completed" }),
    RecipeProgress.find({ child: childId, status: "completed" }),
  ]);

  const gameEntries = await Promise.all(
    (Array.isArray(gameSessions) ? gameSessions : []).map(async (s) => {
      const game = await Game.findById(s.game);
      return {
        type: "game",
        title: game ? game.title : "Unknown game",
        date: s.completedAt || s.createdAt,
        xpEarned: s.xpEarned,
        stars: s.stars,
      };
    })
  );

  const recipeEntries = await Promise.all(
    (Array.isArray(recipeProgresses) ? recipeProgresses : []).map(async (p) => {
      const recipe = await Recipe.findById(p.recipe);
      return {
        type: "recipe",
        title: recipe ? recipe.title : "Unknown recipe",
        date: p.completedAt || p.createdAt,
        xpEarned: p.xpEarned,
        pendingParentVerification: recipe ? recipe.requiresParentVerification && !p.parentVerified : false,
      };
    })
  );

  return [...gameEntries, ...recipeEntries]
    .sort((a, b) => new Date(b.date) - new Date(a.date))
    .slice(0, limit);
}

// ---------------------------------------------------------------------------
// WEEKLY SUMMARY
// ---------------------------------------------------------------------------

async function getWeeklySummary(childId, familyId) {
  const child = await getOwnedChild(childId, familyId);

  const [gameSessions, recipeProgresses, xpTransactions] = await Promise.all([
    GameSession.find({ childProfile: child._id, status: "completed" }),
    RecipeProgress.find({ child: child._id, status: "completed" }),
    XPTransaction.find({ childProfile: child._id }),
  ]);

  const thisWeekGames = (Array.isArray(gameSessions) ? gameSessions : []).filter((s) =>
    withinLastDays(s.completedAt || s.createdAt, 7)
  );
  const thisWeekRecipes = (Array.isArray(recipeProgresses) ? recipeProgresses : []).filter((p) =>
    withinLastDays(p.completedAt || p.createdAt, 7)
  );
  const allXpTransactions = Array.isArray(xpTransactions) ? xpTransactions : [];
  const thisWeekXpTransactions = allXpTransactions.filter((t) => withinLastDays(t.createdAt, 7));
  const thisWeekXp = thisWeekXpTransactions.reduce((sum, t) => sum + t.amount, 0);

  // FIXED (production readiness audit follow-up): this used to be
  // hardcoded to 0 with a comment saying "NutritionLesson module not
  // built yet" -- that module has since been built (see
  // modules/nutrition/), but this dashboard was never updated to read
  // from it. There's no separate NutritionLessonProgress record with its
  // own timestamp to filter by "this week," so this counts distinct
  // lessons via their XPTransaction (sourceType: "lesson") records
  // created in the last 7 days -- the same source-of-truth pattern the
  // rest of this function already uses for games/recipes/XP.
  const nutritionLessonsCompletedThisWeek = new Set(
    thisWeekXpTransactions.filter((t) => t.sourceType === "lesson").map((t) => String(t.sourceId))
  ).size;

  // "Foods tried" this week: distinct non-optional ingredients across
  // recipes completed this week -- a simple, honest proxy given no
  // separate "food discovery" event exists yet.
  const foodsTriedThisWeek = new Set();
  for (const p of thisWeekRecipes) {
    // eslint-disable-next-line no-await-in-loop
    const recipe = await Recipe.findById(p.recipe);
    if (recipe) recipe.ingredients.filter((i) => !i.optional).forEach((i) => foodsTriedThisWeek.add(i.name));
  }

  return {
    weekRange: { start: new Date(Date.now() - SEVEN_DAYS_MS).toISOString(), end: new Date().toISOString() },
    gamesCompleted: thisWeekGames.length,
    recipesCompleted: thisWeekRecipes.length,
    foodsTried: foodsTriedThisWeek.size,
    nutritionLessonsCompleted: nutritionLessonsCompletedThisWeek,
    totalXPEarned: thisWeekXp,
    currentStreak: child.currentStreak,
  };
}

// ---------------------------------------------------------------------------
// LEARNING PROGRESS
// ---------------------------------------------------------------------------

async function getLearningProgress(childId, familyId) {
  const child = await getOwnedChild(childId, familyId);

  const [gameSessions, recipeProgresses] = await Promise.all([
    GameSession.find({ childProfile: child._id, status: "completed" }),
    RecipeProgress.find({ child: child._id, status: "completed" }),
  ]);

  const nutritionTopics = new Set();
  const foodsDiscovered = new Set();
  const cookingSkills = new Set();
  const regionNames = new Set();

  for (const s of Array.isArray(gameSessions) ? gameSessions : []) {
    // eslint-disable-next-line no-await-in-loop
    const game = await Game.findById(s.game);
    if (!game) continue;
    (game.nutritionTopics || []).forEach((t) => nutritionTopics.add(t));
    (game.foodTopics || []).forEach((t) => foodsDiscovered.add(t));
    if (game.state) regionNames.add(game.state);
  }

  for (const p of Array.isArray(recipeProgresses) ? recipeProgresses : []) {
    // eslint-disable-next-line no-await-in-loop
    const recipe = await Recipe.findById(p.recipe);
    if (!recipe) continue;
    (recipe.nutritionLearning || []).forEach((t) => nutritionTopics.add(t));
    (recipe.cookingSkills || []).forEach((s) => cookingSkills.add(s));
    recipe.ingredients.filter((i) => !i.optional).forEach((i) => foodsDiscovered.add(i.name));
  }

  return {
    nutritionTopicsExplored: [...nutritionTopics],
    cookingSkillsLearned: [...cookingSkills],
    foodsDiscovered: [...foodsDiscovered],
    regionsUnlocked: [...regionNames],
  };
}

// ---------------------------------------------------------------------------
// ACTIVITY HISTORY (paginated, merged across types)
// ---------------------------------------------------------------------------

async function getActivityHistory(childId, familyId, query = {}) {
  await getOwnedChild(childId, familyId);
  const { page, limit } = parsePagination(query, { defaultLimit: 15, maxLimit: 50 });

  const all = await buildRecentActivity(childId, 1000); // bounded by realistic per-child volume at MVP scale
  const total = all.length;
  const start = (page - 1) * limit;
  const pageItems = all.slice(start, start + limit);

  return {
    data: {
      games: pageItems.filter((a) => a.type === "game"),
      recipes: pageItems.filter((a) => a.type === "recipe"),
      // Challenges and Achievements modules aren't built yet (see the
      // production audit's roadmap) -- these keys are included now, empty,
      // so a future implementation is additive and never a breaking
      // response-shape change for clients already consuming this endpoint.
      challenges: [],
      achievements: [],
    },
    meta: buildPaginationMeta({ page, limit, total }),
  };
}

// ---------------------------------------------------------------------------
// GROCERY OVERVIEW
// ---------------------------------------------------------------------------

async function getGroceryOverview(familyId) {
  const list = await groceryService.getOrCreateActiveList(familyId);
  return {
    needed: list.items.filter((i) => !i.checked),
    checked: list.items.filter((i) => i.checked),
    customAdditions: list.items.filter((i) => i.custom),
    byRecipe: summarizeByRecipe(list.items),
  };
}

function summarizeByRecipe(items) {
  const map = new Map();
  items.forEach((item) => {
    (item.sourceRecipes || []).forEach((recipeId) => {
      const key = String(recipeId);
      if (!map.has(key)) map.set(key, []);
      map.get(key).push(item.name);
    });
  });
  return Array.from(map.entries()).map(([recipeId, ingredientNames]) => ({ recipeId, ingredientNames }));
}

// ---------------------------------------------------------------------------
// SETTINGS (read-model; writes reuse the existing users/children endpoints
// so preference logic lives in exactly one place -- see the design doc)
// ---------------------------------------------------------------------------

async function getSettings(user, familyId) {
  const children = await ChildProfile.find({ familyId, deletedAt: null });
  return {
    notificationPreferences: user.notificationPreferences,
    privacy: {
      emailVerified: user.emailVerified,
      accountStatus: user.status,
      dataExportOrDeleteEndpoint: "DELETE /api/v1/users/me",
    },
    children: (Array.isArray(children) ? children : []).map((c) => ({
      _id: c._id,
      displayName: c.displayName,
      accessibilityPreferences: c.preferences?.accessibilityPreferences,
    })),
  };
}

module.exports = {
  getOverview,
  getWeeklySummary,
  getLearningProgress,
  getActivityHistory,
  getGroceryOverview,
  getSettings,
};
